service: blogAPI

app: database-app
org: harshmohan813

frameworkVersion: '2'

custom:
  dynamoDB:
    BLOGS_TABLE: blogsTable

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221
  region: us-east-1
  environment:
    ${self:custom.dynamoDB}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DescribeItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "*"

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: "S"
          - AttributeName: SK
            AttributeType: "S"
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:custom.dynamoDB.BLOGS_TABLE}

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    description: Homepage of API.
    events:
     - httpApi:
         path: /
         method: get
  createPost:
    handler: handler.createPost
    events:
    - http:
        path: /post
        method: post
  getAllPosts:
    handler: handler.getAllPosts
    events:
    - http:
        path: /posts
        method: get
  # candidateSubmission:
  #   handler: api/candidate.submit
  #   memorySize: 128
  #   description: Submit candidate information and starts interview process.
  #   events:
  #     - http:
  #         path: candidates
  #         method: post
  # createBlog:
  #   handler: blog/requests.createBlog
  #   events:
  #    - httpApi:
  #        path: /blog/create
  #        method: post
  # deleteBlog:
  #     handler: blog/requests.deleteBlog
  #     events:
  #     - httpApi:
  #         path: /blog/delete
  #         method: delete
  # updateBlog:
  #   handler: blog/requests.updateBlog
  #   events:
  #    - httpApi:
  #        path: /blog/update
  #        method: patch
  # viewBlog:
  #     handler: blog/requests.viewBlog
  #     events:
  #     - httpApi:
  #         path: /blog/view
  #         method: get