service: blogAPI

app: database-app
org: harshmohan813

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
     - httpApi:
         path: /
         method: get
  createBlog:
    handler: handler.createBlog
    events:
     - httpApi:
         path: /blog/create
         method: post
  deleteBlog:
      handler: handler.deleteBlog
      events:
      - httpApi:
          path: /blog/delete
          method: delete
  updateBlog:
    handler: handler.updateBlog
    events:
     - httpApi:
         path: /blog/update
         method: patch
  viewBlog:
      handler: handler.viewBlog
      events:
      - httpApi:
          path: /blog/view
          method: get